"""
mesh_processing.py — GLB cleanup, canonical orientation, metric scaling, re-UV, export.
========================================================================================
Architecture — 10-step pipeline (CPU-only, no GPU needed):

  1.  trimesh.load(process=False)   → Scene  → largest geometry
  2.  Remove floaters               → mesh.split() + area threshold
  3.  pymeshfix                     → fix non-manifold, fill holes
  4.  Taubin smooth (PyMeshLab)     → gentle smoothing, no shrinkage
  5.  Isotropic remesh (PyMeshLab)  → uniform triangle distribution
  6.  Decimate (PyMeshLab)          → ~40 K triangles for browser rendering
  7.  Fix normals (trimesh)         → consistent winding
  8.  xatlas re-UV                  → new UV atlas (topology changed — old UVs invalid)
  9.  Canonical orient              → apply_obb() + axis permute (longest→Y, shortest→Z)
  10. Metric scale                  → diagonal transform matrix (mm units)
  11. trimesh GLB export            → embeds PBR texture in binary GLB

Key gotchas (from research):
  - PyMeshLab CANNOT save GLB — use PLY intermediate → trimesh for final export.
  - pymeshfix rebuilds vertex array → original UVs invalid → always re-UV with xatlas.
  - trimesh.load(force='mesh') strips textures → always use trimesh.load() only.
  - After non-uniform scale, normals are auto-invalidated by trimesh (cached property).
  - scene.dump(concatenate=True) is deprecated (Apr 2025) → use scene.to_mesh().
"""

from __future__ import annotations

import os
import tempfile
from dataclasses import dataclass, field
from pathlib import Path
from typing import List, Optional, Tuple

import numpy as np
import pymeshfix  # type: ignore[import]
import pymeshlab as pml  # type: ignore[import]
import trimesh  # type: ignore[import]
import xatlas  # type: ignore[import]
from PIL import Image

from src.config import cfg
from src.gemini_client import ProductDimensions


# ---------------------------------------------------------------------------
# Result dataclass
# ---------------------------------------------------------------------------


@dataclass
class MeshProcessingResult:
    """
    Output of the mesh processing stage.

    Attributes:
        final_glb_path:  Path to the cleaned, oriented, metric-scaled GLB.
        face_count:      Triangle count in the final mesh.
        vertex_count:    Vertex count (may differ from face_count/3 due to xatlas seam verts).
        extents_mm:      Bounding box dimensions [width, height, depth] in millimeters.
        is_watertight:   True if the final mesh has no boundary edges.
        stats_table:     Formatted summary string for display.
    """

    final_glb_path: Path
    face_count: int
    vertex_count: int
    extents_mm: List[float]
    is_watertight: bool
    stats_table: str


# ---------------------------------------------------------------------------
# Helper: PLY round-trip through PyMeshLab
# ---------------------------------------------------------------------------


def _meshlab_process(mesh: trimesh.Trimesh, target_faces: int = 40_000) -> trimesh.Trimesh:
    """
    Apply PyMeshLab cleanup + smoothing + decimation to a trimesh.Trimesh.

    Uses PLY as the intermediate format because:
      - PyMeshLab cannot load/save GLB.
      - PLY preserves vertex/face geometry reliably (no UV, which is fine —
        UVs will be regenerated by xatlas after this step).

    Sequence:
      a. Remove unreferenced vertices + duplicate faces + null faces
      b. Repair non-manifold edges and vertices
      c. Taubin smooth (lambda=0.5, mu=-0.53, 5 iterations) — no shrinkage
      d. Decimate to target_faces using quadric edge collapse

    Args:
        mesh:         Input trimesh.Trimesh (geometry only — UVs will be lost).
        target_faces: Target triangle count after decimation.

    Returns:
        Cleaned trimesh.Trimesh (geometry only, no UVs).
    """
    ms = pml.MeshSet()

    with tempfile.NamedTemporaryFile(suffix=".ply", delete=False) as f:
        tmp_in = f.name
    with tempfile.NamedTemporaryFile(suffix=".ply", delete=False) as f:
        tmp_out = f.name

    try:
        # Export geometry only (texture is invalidated anyway by topology ops)
        mesh.export(tmp_in)
        ms.load_new_mesh(tmp_in)

        # --- Cleanup ---
        ms.meshing_remove_unreferenced_vertices()
        ms.meshing_remove_duplicate_faces()
        ms.meshing_remove_null_faces()
        ms.meshing_repair_non_manifold_edges(method=0)  # 0 = remove faces
        ms.meshing_repair_non_manifold_vertices(vertdispratio=0)

        # --- Taubin smooth --- (λ=0.5 forward, μ=-0.53 backward per Taubin 1995)
        ms.apply_coord_taubin_smoothing(
            lambda_=0.5, mu=-0.53, stepsmoothnum=5, selected=False
        )

        # --- Decimate ---
        ms.meshing_decimation_quadric_edge_collapse(
            targetfacenum=target_faces,
            qualitythr=0.3,
            preservenormal=True,
            optimalplacement=True,
            preserveboundary=False,
        )

        ms.save_current_mesh(tmp_out)
        result = trimesh.load_mesh(tmp_out, process=False)

    finally:
        os.unlink(tmp_in)
        os.unlink(tmp_out)

    return result


# ---------------------------------------------------------------------------
# Helper: pymeshfix non-manifold repair
# ---------------------------------------------------------------------------


def _fix_nonmanifold(mesh: trimesh.Trimesh) -> trimesh.Trimesh:
    """
    Fix non-manifold topology and fill small boundary holes using pymeshfix.

    pymeshfix rebuilds the vertex array — original UV coordinates are
    invalidated after this step.  xatlas re-UV must follow.

    Args:
        mesh: Input trimesh.Trimesh.

    Returns:
        Repaired trimesh.Trimesh (geometry only).
    """
    tin = pymeshfix.PyTMesh()
    tin.load_array(mesh.vertices, mesh.faces)
    tin.fix_connectivity()
    tin.fill_small_boundaries(refine=True)
    verts, faces = tin.return_arrays()
    return trimesh.Trimesh(vertices=verts, faces=faces, process=False)


# ---------------------------------------------------------------------------
# Helper: xatlas UV generation
# ---------------------------------------------------------------------------


def _remap_uvs(
    mesh: trimesh.Trimesh,
    original_texture: Optional[Image.Image],
) -> trimesh.Trimesh:
    """
    Generate a new UV atlas with xatlas and re-attach the original texture.

    After decimation or pymeshfix, the vertex array is renumbered — the old
    UV mapping is no longer valid.  xatlas.parametrize() generates a new
    atlas.  We re-assign the original (pre-topology-change) texture image
    to the new UV layout (fast path — no rebake).

    If no original_texture is available (e.g., input mesh had no texture),
    the mesh is returned with geometry only (no visual).

    Args:
        mesh:             Decimated trimesh.Trimesh (no valid UVs).
        original_texture: PIL Image from the original Hunyuan3D texture, or None.

    Returns:
        trimesh.Trimesh with new UV mapping (and texture if available).
    """
    vmapping, indices, uvs = xatlas.parametrize(mesh.vertices, mesh.faces)

    new_verts = mesh.vertices[vmapping]
    new_mesh = trimesh.Trimesh(vertices=new_verts, faces=indices, process=False)

    if original_texture is not None:
        material = trimesh.visual.material.PBRMaterial(
            baseColorFactor=[1.0, 1.0, 1.0, 1.0],
            baseColorTexture=original_texture,
            metallicFactor=0.0,
            roughnessFactor=1.0,
        )
        new_mesh.visual = trimesh.visual.TextureVisuals(uv=uvs, material=material)

    return new_mesh


# ---------------------------------------------------------------------------
# Helper: canonical orientation
# ---------------------------------------------------------------------------


def _canonical_orient(mesh: trimesh.Trimesh) -> trimesh.Trimesh:
    """
    Orient mesh so that:
      - Longest OBB axis → Y (height / standing dimension)
      - Middle OBB axis  → X (width)
      - Shortest OBB axis → Z (depth / thickness)
      - Centroid at origin

    Uses trimesh.apply_obb() (angle-sampling OBB, not pure PCA) for robustness.
    The axis-to-slot assignment is done via argsort of the OBB extents.

    Note: The orientation convention is arbitrary within 90° — sign ambiguity
    (e.g., which end is 'top') requires domain knowledge and is not resolved
    in this automated step.

    Args:
        mesh: trimesh.Trimesh to orient (modified in-place).

    Returns:
        The same mesh after in-place transformation.
    """
    # Step 1: apply_obb() aligns OBB with world axes, centers at origin
    mesh.apply_obb()

    # Step 2: determine which current axis corresponds to longest/middle/shortest
    extents = mesh.bounding_box.extents  # [X_size, Y_size, Z_size]
    order = np.argsort(extents)          # ascending: [smallest_idx, middle_idx, longest_idx]

    # Build permutation matrix:
    # longest (order[2]) → new Y (axis 1)
    # middle  (order[1]) → new X (axis 0)
    # shortest(order[0]) → new Z (axis 2)
    P3 = np.zeros((3, 3))
    P3[1, order[2]] = 1.0  # new Y ← old longest
    P3[0, order[1]] = 1.0  # new X ← old middle
    P3[2, order[0]] = 1.0  # new Z ← old shortest

    P4 = np.eye(4)
    P4[:3, :3] = P3
    mesh.apply_transform(P4)

    # Step 3: re-center (permutation may shift centroid slightly)
    mesh.apply_translation(-mesh.centroid)

    return mesh


# ---------------------------------------------------------------------------
# Helper: metric scaling
# ---------------------------------------------------------------------------


def _apply_metric_scale(
    mesh: trimesh.Trimesh,
    width_mm: float,
    height_mm: float,
    depth_mm: float,
) -> trimesh.Trimesh:
    """
    Scale mesh to exact real-world millimeter dimensions using a non-uniform
    diagonal transform matrix.

    After canonical_orient, the mesh extents are:
      X = width, Y = height, Z = depth (shortest dimension)

    The scale factors are:
      sx = width_mm  / current_X
      sy = height_mm / current_Y
      sz = depth_mm  / current_Z

    This may introduce slight anisotropic distortion, which is intentional —
    Hunyuan3D often inflates thickness 1.5–3× so we correct it here.

    Args:
        mesh:      Canonically-oriented trimesh.Trimesh.
        width_mm:  Target width in mm.
        height_mm: Target height in mm.
        depth_mm:  Target depth in mm.

    Returns:
        Scaled mesh (modified in-place and returned).
    """
    cx, cy, cz = mesh.bounding_box.extents

    if any(e == 0 for e in (cx, cy, cz)):
        raise ValueError(
            f"Mesh has zero extent along at least one axis: "
            f"extents={mesh.bounding_box.extents}. Cannot scale."
        )

    S = np.diag([width_mm / cx, height_mm / cy, depth_mm / cz, 1.0])
    mesh.apply_transform(S)
    return mesh


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------


def run_mesh_processing(
    glb_path: str | Path,
    dimensions: Optional[ProductDimensions] = None,
    target_faces: int = 40_000,
    output_name: str = "phone_final.glb",
) -> MeshProcessingResult:
    """
    Full mesh cleanup, orientation, metric scaling, and GLB export.

    Steps (in research-specified order):
      1.  Load GLB with trimesh.load(process=False) → extract largest geometry.
      2.  Save original texture image (invalidated by topology ops).
      3.  Remove floater components (area < 1% of largest).
      4.  pymeshfix: fix non-manifold edges, fill holes.
      5.  PyMeshLab: Taubin smooth + isotropic remesh + decimate → ~40K faces.
      6.  trimesh.repair.fix_normals(multibody=True).
      7.  xatlas re-UV + re-attach original texture.
      8.  Canonical orientation (longest→Y, middle→X, shortest→Z).
      9.  Metric scale to real-world mm dimensions (from ProductDimensions).
      10. Export as GLB with embedded PBR texture.

    Args:
        glb_path:     Path to the raw Hunyuan3D GLB output.
        dimensions:   ProductDimensions from Gemini grounded search.
                      If None, the mesh is exported at its current (arbitrary) scale.
        target_faces: Triangle count after decimation.  40K is good for browser WebGL.
        output_name:  Filename for the final GLB in cfg.OUTPUT_DIR.

    Returns:
        MeshProcessingResult with path, stats, and formatted stats table.
    """
    output_path = cfg.OUTPUT_DIR / output_name
    glb_path = Path(glb_path)

    # --- Step 1: Load ---
    print(f"[mesh_processing] Loading {glb_path}...")
    scene = trimesh.load(str(glb_path), process=False)
    if isinstance(scene, trimesh.Scene):
        all_geoms = list(scene.geometry.values())
        mesh: trimesh.Trimesh = max(all_geoms, key=lambda m: m.area)
    else:
        mesh = scene

    print(
        f"[mesh_processing] Loaded: {len(mesh.faces)} faces, {len(mesh.vertices)} vertices"
    )

    # --- Step 2: Preserve original texture ---
    original_texture: Optional[Image.Image] = None
    if (
        hasattr(mesh.visual, "material")
        and hasattr(mesh.visual.material, "baseColorTexture")
        and mesh.visual.material.baseColorTexture is not None
    ):
        original_texture = mesh.visual.material.baseColorTexture
        print("[mesh_processing] Original PBR texture preserved.")
    else:
        print("[mesh_processing] No PBR texture found — geometry-only processing.")

    # --- Step 3: Remove floaters ---
    components = mesh.split(only_watertight=False)
    if len(components) > 1:
        components = sorted(components, key=lambda c: c.area, reverse=True)
        largest_area = components[0].area
        kept = [c for c in components if c.area >= 0.01 * largest_area]
        mesh = trimesh.util.concatenate(kept) if len(kept) > 1 else kept[0]
        print(
            f"[mesh_processing] Floater removal: kept {len(kept)}/{len(components)} components."
        )

    # --- Step 4: pymeshfix ---
    print("[mesh_processing] pymeshfix: repairing non-manifold topology...")
    mesh = _fix_nonmanifold(mesh)
    print(
        f"[mesh_processing] Post-fix: {len(mesh.faces)} faces, "
        f"{len(mesh.vertices)} vertices"
    )

    # --- Step 5: PyMeshLab cleanup + smooth + decimate ---
    print(f"[mesh_processing] PyMeshLab: smooth + decimate to ~{target_faces} faces...")
    mesh = _meshlab_process(mesh, target_faces=target_faces)
    print(
        f"[mesh_processing] Post-decimate: {len(mesh.faces)} faces, "
        f"{len(mesh.vertices)} vertices"
    )

    # --- Step 6: Fix normals ---
    trimesh.repair.fix_normals(mesh, multibody=True)

    # --- Step 7: xatlas re-UV ---
    print("[mesh_processing] xatlas: generating new UV atlas...")
    mesh = _remap_uvs(mesh, original_texture)
    print(f"[mesh_processing] UV atlas generated. Vertices: {len(mesh.vertices)}")

    # --- Step 8: Canonical orientation ---
    print("[mesh_processing] Canonical orientation (longest→Y, middle→X, shortest→Z)...")
    mesh = _canonical_orient(mesh)
    extents = mesh.bounding_box.extents
    print(f"[mesh_processing] Oriented extents (raw units): {extents}")

    # --- Step 9: Metric scaling ---
    if dimensions is not None and all(
        v is not None
        for v in (dimensions.width_mm, dimensions.height_mm, dimensions.depth_mm)
    ):
        print(
            f"[mesh_processing] Scaling to "
            f"{dimensions.width_mm}×{dimensions.height_mm}×{dimensions.depth_mm} mm..."
        )
        mesh = _apply_metric_scale(
            mesh,
            width_mm=dimensions.width_mm,
            height_mm=dimensions.height_mm,
            depth_mm=dimensions.depth_mm,
        )
    else:
        print(
            "[mesh_processing] No dimensions provided — mesh exported at arbitrary scale."
        )

    final_extents = list(mesh.bounding_box.extents)

    # --- Step 10: Export ---
    print(f"[mesh_processing] Exporting to {output_path}...")
    mesh.export(str(output_path))

    # Build stats
    is_watertight = mesh.is_watertight
    stats_table = (
        f"\n{'='*50}\n"
        f"  FINAL MESH STATISTICS\n"
        f"{'='*50}\n"
        f"  Output path   : {output_path}\n"
        f"  Faces         : {len(mesh.faces):,}\n"
        f"  Vertices      : {len(mesh.vertices):,}\n"
        f"  Watertight    : {'✅ Yes' if is_watertight else '⚠️  No'}\n"
        f"  Extents (mm)  : W={final_extents[0]:.1f}  "
        f"H={final_extents[1]:.1f}  D={final_extents[2]:.1f}\n"
        f"{'='*50}\n"
    )
    print(stats_table)

    return MeshProcessingResult(
        final_glb_path=output_path,
        face_count=len(mesh.faces),
        vertex_count=len(mesh.vertices),
        extents_mm=final_extents,
        is_watertight=is_watertight,
        stats_table=stats_table,
    )
